
== Introduction

Red Hat Ansible Automation Platform on Microsoft Azure offers all the benefits of Ansible automation, deployed in your Azure cloud. Red Hat Ansible Automation Platform on Microsoft Azure is a managed application that you can deploy directly from your Azure Marketplace portal.

This managed application is fully supported by Red Hat, providing all the tools you need to deploy enterprise-wide automation. It also integrates with native Azure services and the full Ansible collection for Microsoft Azure, co-developed and security tested by Microsoft and Red Hat. 


== Overview

In this hands on lab you will:

* Deploy Ansible Ansible Platform on Microsoft Azure from the Azure Marketplace
* Create an Azure Service Principal to authenticate against Azure resources
* Learn how to leverage the Private Automation Hub
* Deprovision the resources you create


== Prerequisites

. Red Hat Account
     You will need a valid Red Hat SSO account in order to retrieve an Ansible entitlement once the application is deployed.  Please ensure that you are able to login to console.redhat.com successfully.  Mostly likely this is <yourhandle@redhat.com> 

. Azure Environment Details
     Once you have “Ordered” the environment, you will receive an email providing you with the necessary information for the Azure subscription that you have been assigned for this lab/demo, as well as any other Azure details.  You will use your @redhat.com email address to login to Microsoft Azure via SSO.